### ISSUE TITLE
matplotlib on CLI

### ISSUE THREAD

**Issue by lvhengani** [acolite/acolite_ls2#1]
Hi, Thanks you for this wonderful tool. Is is possible to avoid importing Matplotlib and also omitting the imports for any python graphic user interface libraries for command-line interface (CLI) runs?

**Comment by acolite** [comment]
ACOLITE relies on matplotlib for outputting plots and mapped images. It should however be possible to  run just the processing without any figure generation. I added an additional _--nogfx_ option that skips the matplotlib import in the launcher (which was needed to select the Agg backend), and disables any outputs that use matplotlib. This option should be used in addition to _--cli_ as some CLI users may require output plots. For example:

python launch_acolite.py --cli --nogfx --settings=$file

Note that I renamed the _acolite.py_ launcher to _launch_acolite.py to_ avoid an issue with PyInstaller for the binary distribution. Does this update work for you?

**Comment by lvhengani** [comment]
Thank you for the update and for coming back to me. I think this will work. I will test and come back to you. I am using ACOLITE in a docker-container and it is a nightmare to use matplotlib in a container. The other reason is when using docker-containers, its best to use minimal memory usage as possible.

**Comment by lvhengani** [comment]
Hi I tested  and it working fine. Thank you.
