### ISSUE TITLE
The problem of sentinel3 auxiliary data 

### ISSUE THREAD

**Issue by ticvie** [acolite/acolite_ls2#13]
Hello Quinten
In the process of using acolite to process, I have two questions that I don't understand, about sentinel3 auxiliary data. The first question is, in the "acolite/data/PP/LUT/" directory, what data is the file in the "RSKY" folder, which is the same as the file in the "ACOLITE-LUT-202003-MOD1" folder What's the difference? The second question is, what does "switch_water lower_water upper_water switch_land lower_land upper_land" in the "band_info_olci.txt" file mean?
Looking forward for your reply, thank you！
Ticvie

**Comment by acolite** [comment]
Hi Ticvie

The LUTs are not the same files, one ("ACOLITE-LUT") contains the atmospheric parameters, the other ("ACOLITE-RSKY") the reflectance of the air-water interface as modeled with OSOAA. 

The band_info_olci.txt contains the settings for the smile correction. Switch water enables the application of the smile correction for that band, switch land for land. Only switch water is used at the moment, since I copied this file from elsewhere (ocssw I believe) I chose not to modify it. The lower and upper parameters give the band indices for the bounding bands used in the smile correction.

You can find info on both these things in Appendix A of https://www.sciencedirect.com/science/article/pii/S003442572100002X and references therein.

Hope this is clear!

Quinten

p.s. Keep in mind I am working on a rewrite of ACOLITE and this will improve the integration of the S3 code. The "official" release of S3 processing will be in that version. But please let me know if you have any issues!

**Comment by ticvie** [comment]
Hello Quinten
First of all, thank you very much for your reply, I have one more question. Whether there is a calculation process for TOA data in the processing program of sentinel3, I have not found it yet.
Best wishes
Ticvie





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acolite/acolite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午3:53
收件人:&nbsp;"acolite/acolite"<acolite@noreply.github.com&gt;;
抄送:&nbsp;"Ticvie"<915682061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [acolite/acolite] The problem of sentinel3 auxiliary data  (#13)





 
Hi Ticvie
 
The LUTs are not the same files, one ("ACOLITE-LUT") contains the atmospheric parameters, the other ("ACOLITE-RSKY") the reflectance of the air-water interface as modeled with OSOAA.
 
The band_info_olci.txt contains the settings for the smile correction. Switch water enables the application of the smile correction for that band, switch land for land. Only switch water is used at the moment, since I copied this file from elsewhere (ocssw I believe) I chose not to modify it. The lower and upper parameters give the band indices for the bounding bands used in the smile correction.
 
You can find info on both these things in Appendix A of https://www.sciencedirect.com/science/article/pii/S003442572100002X and references therein.
 
Hope this is clear!
 
Quinten
 
p.s. Keep in mind I am working on a rewrite of ACOLITE and this will improve the integration of the S3 code. The "official" release of S3 processing will be in that version. But please let me know if you have any issues!

**Comment by ticvie** [comment]
Hello Quinten
First of all, thank you very much for your reply, I have two more questions. The first question is whether there is a calculation process for TOA data in the processing program of sendinel3, I haven't found it yet. The second question is, what is the function of smile correction, and why is it necessary to perform smile correction?
best wishes
Ticvie





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "acolite/acolite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午3:53
收件人:&nbsp;"acolite/acolite"<acolite@noreply.github.com&gt;;
抄送:&nbsp;"Ticvie"<915682061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [acolite/acolite] The problem of sentinel3 auxiliary data  (#13)





 
Hi Ticvie
 
The LUTs are not the same files, one ("ACOLITE-LUT") contains the atmospheric parameters, the other ("ACOLITE-RSKY") the reflectance of the air-water interface as modeled with OSOAA.
 
The band_info_olci.txt contains the settings for the smile correction. Switch water enables the application of the smile correction for that band, switch land for land. Only switch water is used at the moment, since I copied this file from elsewhere (ocssw I believe) I chose not to modify it. The lower and upper parameters give the band indices for the bounding bands used in the smile correction.
 
You can find info on both these things in Appendix A of https://www.sciencedirect.com/science/article/pii/S003442572100002X and references therein.
 
Hope this is clear!
 
Quinten
 
p.s. Keep in mind I am working on a rewrite of ACOLITE and this will improve the integration of the S3 code. The "official" release of S3 processing will be in that version. But please let me know if you have any issues!

**Comment by acolite** [comment]
Hi Ticvie

There is no separate function to compute TOA reflectance, but there is a TOA radiance->reflectance conversion integrated in acolite_olci.py

The individual pixels of the OLCI detectors have slight differences in their central wavelength. This effect is called smile, and the smile correction tries to align the measurements made at slightly different wavelengths to a single reference wavelength. You can find more info here: https://earth.esa.int/documents/700255/707220/MERIS_Smile_Effect.pdf

Quinten

**Comment by ticvie** [comment]
Hi Quinten
I have received your email, thank you again for your help.
best wishes

Ticvie




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acolite/acolite_ls2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 晚上6:00
收件人:&nbsp;"acolite/acolite_ls2"<acolite_ls2@noreply.github.com&gt;;
抄送:&nbsp;"Ticvie"<915682061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [acolite/acolite_ls2] The problem of sentinel3 auxiliary data  (#13)





 
Hi Ticvie
 
There is no separate function to compute TOA reflectance, but there is a TOA radiance-&gt;reflectance conversion integrated in acolite_olci.py
 
The individual pixels of the OLCI detectors have slight differences in their central wavelength. This effect is called smile, and the smile correction tries to align the measurements made at slightly different wavelengths to a single reference wavelength. You can find more info here: https://earth.esa.int/documents/700255/707220/MERIS_Smile_Effect.pdf
 
Quinten
