### ISSUE TITLE
Issue with l8_output_lt_tirs key in setu dictionary

### ISSUE THREAD

**Issue by DrMenny** [acolite/acolite_ls2#4]
I updated the code but this error happens while processing Sentinel2 products. I think it's related to the commit https://github.com/acolite/acolite/commit/87991641336e02d6e23355ce9eb2e6baa59d3ac7

![image](https://user-images.githubusercontent.com/45639805/62119739-7cdf8880-b2c0-11e9-9263-e6948eb539cb.png)

**Comment by acolite** [comment]
Should be fixed now, by adding l8_output_lt_tirs=False in the defaults file.

**Comment by DrMenny** [comment]
Thank you!
