### ISSUE TITLE
'float' object cannot be interpreted as an integer error in range function

### ISSUE THREAD

**Issue by omerekmekcioglu** [acolite/acolite_ls2#9]
Hi, 

I am trying to search the optimal solution in a one set of parameter range. However, the range function does not allow float. 

I could not find a way to solve. 

Here my code; 
...
param_grid = { 
    'penalty': range(2, 4, 0.1)
}

algorithm = GeneticAlgorithm()
algorithm.setParameters(NP=50, Ts=5, Mr=0.25)
...

I will be very happy if anyone can help me to get over it!

**Comment by acolite** [comment]
This does not look like it is an ACOLITE issue! Closing.
